### ISSUE TITLE
Single mode von Mises model

### ISSUE THREAD

**Issue by fferroni** [sergeyprokudin/deep_direct_stat#1]
Hi,

Great work and nice meeting you at ECCV.
Looking at the infinite_mixture model in the repo, _mc_loss can easily be used also for the single mode von mises model - kappa is predicted by the basis network, correct?

Also, to model an unbounded regression task, like size or location, one can simply replace the von Mises distribution by a Normal distribution and use the same pipeline, correct?

Cheers,
Francesco

**Comment by sergeyprokudin** [comment]
Hi Francesco,

Thanks a lot, and was nice talking to you as well! 

Regarding mc_loss - yes, actually setting n_samples=1 in the model will make it behave like single von Mises. But I can also push myself a little bit and upload a single mode model if you are interested :)

Regarding non-circular tasks - yes, you can simply switch to normal or any other distribution. You'll only need to provide the likelihood function for computing the loss (for Gaussian there are  of course already implementations in tf).

Hope these helps! Let me know if you have any other questions,

Best, Sergey

**Comment by fferroni** [comment]
> upload a single mode model if you are interested

well, can't say I am not but I guess I can simplify it myself :)
