### ISSUE TITLE
Preprocessed PASCAL3D+ data missing

### ISSUE THREAD

**Issue by LuisArmandoPerez** [sergeyprokudin/deep_direct_stat#2]
Hello, I am trying to load the PASCAL3D+ dataset with the tools provided in this repository but the link to Google Drive is not found :( is there any chance that this could be restored?

**Comment by sergeyprokudin** [comment]
Hi Luis,

Thanks for pointing this out! I've re-uploaded the dataset and updated the link. You can now find it here:

https://drive.google.com/open?id=1baI_QUNuGN9DJGgaOWubbservgQ6Oc4x

**Comment by LuisArmandoPerez** [comment]
Thank you for the quick response 😄, this is very useful!
