### ISSUE TITLE
Pretrained Models 

### ISSUE THREAD

**Issue by b7leung** [sergeyprokudin/deep_direct_stat#3]
Thanks for posting your code! The work seems very interesting. The google drive link ( https://drive.google.com/file/d/1H29OVZn5jdlQDQt6_R7eK7WOEinmgxcy/view?usp=sharing ) for the pretrained model seems to be broken. Could it be fixed?

**Comment by sergeyprokudin** [comment]
Hi Brandon! 

Thanks for your interest. I've just uploaded [the updated checkpoint ](https://drive.google.com/file/d/1_Xxl5HbuZFuM66WkqZlcGcq9Qb5uZgRL/view?usp=sharing)for the "aeroplane" class used in the ipython notebook. Let me know if it works for you.

Best,
Sergey
