### ISSUE TITLE
Preprocessed Pascal3D+ dataset link

### ISSUE THREAD

**Issue by dvtailor** [sergeyprokudin/deep_direct_stat#4]
Hi, the link to download your preprocessed Pascal3D+ dataset is not working. If you have a copy somewhere, would be great to re-upload (I know the project is several years old!)

**Comment by sergeyprokudin** [comment]
Hi @dvtailor,

Unfortunately, the preprocessed dataset link is indeed no longer available, and I don’t seem to have a backup for it. 

Apologies for the inconvenience,

~Sergey

**Comment by dvtailor** [comment]
Hi @sergeyprokudin, no problem, thanks for taking the time to look into it.
